version: "3"
services:
    fapp:
        env_file: .env
        container_name: ${container_name_flask}
        build: ./flask_app
        volumes:
            - ./flask_app/config/:${container_mountpoint_flask}
        ports:
            - "${port_of_flask}"
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true 
        command: uwsgi --ini ${container_mountpoint_flask}uwsgi.ini

    nginx:
        env_file: .env
        container_name: ${container_name_nginx}
        image: nginx:${version_of_nginx}
        volumes:
            - ./nginx/config/flask_app.conf:/etc/nginx/conf.d/flask_app.conf
        ports:
            - "${port_of_nginx}"
        environment:
            TZ: "Asia/Tokyo"
        stdin_open: true
        tty: true
